### PR TITLE
fix and add

### PR DESCRIPTION
**Pull request by gesori-pro**
Add-  Ability Success Rate +55%
Add-  Ability Success Rate +60%
Fix - Mark Joyo (HP 5 -> 50)

### CODE REVIEW

**Comment by malulleybovo** [comment]
Thank you for submitting this pull request.
I see that you are trying to include new success rate items to the project. In order to do that, there are a few steps that need to be completed.
First, you add them to the affixData.js in the proper location, including all the necessary fields such as "ref" (it seems you have done this part correctly).
Second, to show the options within the Assistant, you are required to supply all the necessary text that describes the new options. This text is supposed to be included in lang.js, where all the language related text of the application is. Note that you will be required to supply text for all supported languages (at the moment it supports english and japanese).

I suggest you execute rebuild.bat (check out CONTRIBUTING.md for more information). This will build the application, and warn you of anything it knows for sure is missing. At the moment, your pull request is spitting out a build error:
image
Please make sure the application builds successfully before submitting a pull request. Once the errors are addressed, this pull request will undergo review.

Once again, thank you for the pull request.

**Comment by gesori-pro** [comment]
image
it's done :)

**Review by malulleybovo — APPROVED** [review]
Your pull request passed the review and will now be included in the project. I noticed that you tried to include Korean language support. That would be a very nice addition, but that deserves a separate pull request. If you wish to pursue this idea, refer to issue https://github.com/malulleybovo/PSO2AffixingAssistant/issues/30 where I explained how that could be done.

**Comment by gesori-pro** [comment]
> 
> 
> Your pull request passed the review and will now be included in the project. I noticed that you tried to include Korean language support. That would be a very nice addition, but that deserves a separate pull request. If you wish to pursue this idea, refer to issue #30 where I explained how that could be done.

okay :)

**Pull request merged**
